### ISSUE TITLE
[Bug Report] Tab State lost when moving tabs between windows.

### ISSUE THREAD

**Issue by MintMain21** [igorlogius/load-background-tabs-on-select#3]
If I have multiple unloaded tabs in a window, select them all, and move them into another window, the tab state will be lost (IE: The unloaded tab will become a blank tab and the actual URL will be lost). 

Might be a conflict with some other extensions I use (Tiled Tab Groups, Tab Mover, etc), but considering how infamously finicky unloaded tabs can be, it might be something that can be fixed in this extension.

**Comment by igorlogius** [comment]
I'll try to reproduce the issue on my side, and come back with my results.
