### ISSUE TITLE
Does not work in Firefox 121.

### ISSUE THREAD

**Issue by srjjgm** [igorlogius/load-background-tabs-on-select#4]
Please, fix it.

**Comment by igorlogius** [comment]
I'll check.

**Comment by igorlogius** [comment]
Seems to work fine with 121.0 and the default configuration.


https://github.com/igorlogius/load-background-tabs-on-select/assets/67047467/64b205e4-6536-4261-b7a3-1a6d91409c40

So my guess would be you or some programm on your system made some modifications to the browser settings (`about:config` or other), but if you can reproduce your issue in a second empty/unmodified profile, let me know and i'll try to look further into the issue.

**Comment by srjjgm** [comment]
Thanks for the quick response.
        So
          it looks like the problem is with me. I use the Tab Mix Plus
          extension, through userChromeJS
          (https://github.com/xiaoxiaoflood/firefox-scripts/).
        I
          disabled TMP to test and your extension worked normally.
      But until Firefox
          120, both extensions worked without any problems.
          
        
    
        
    igorlogius escreveu em 20/12/2023,
      15:57:
    
    
      
      Seems to work fine with 121.0 and the default
        configuration.
      https://github.com/igorlogius/load-background-tabs-on-select/assets/67047467/64b205e4-6536-4261-b7a3-1a6d91409c40
      So my guess would be you or some programm on your
        system made some modifications to the browser settings (about:config or other), but if you
        can reproduce your issue in a second empty/unmodified profile,
        let me know and i'll try to look further into the issue.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/igorlogius/load-background-tabs-on-select/issues/4#issuecomment-1864985452",
"url": "https://github.com/igorlogius/load-background-tabs-on-select/issues/4#issuecomment-1864985452",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by igorlogius** [comment]
>  But until Firefox 120, both extensions worked without any problems.

My current best guess would be ... if neither `Load background tabs on select` or `Tab Mix Plus` was changed/updated, that something within Firefox 120 changed (maybe in relation to the userChrome script.)

I sadly can not support compatability with other extensions or scripting solutions, since i am only a single developers, but if you do find a workaround or solution, feel free to post it here so others have an easier time finding it.

**Comment by srjjgm** [comment]
Problem solved.
    I updated Tab Mix Plus to the newest test version made available by
    the author, and Load Background Tabs on Select worked normally.
    Thank you for your attention and I apologize for bothering you with
    a problem that was not yours.
    Thank you very much!
    
    
    
    igorlogius escreveu em 21/12/2023,
      06:21:
    
    
      
      
        But until Firefox 120, both extensions worked
          without any problems.
      
      My current best guess would be ... if neither Load background tabs on select or Tab Mix Plus was changed/updated,
        that something within Firefox 120 changed (maybe in relation to
        the userChrome script.)
      I sadly can not support compatability with other
        extensions or scripting solutions, since i am only a single
        developers, but if you do find a workaround or solution, feel
        free to post it here so others have an easier time finding it.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were assigned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/igorlogius/load-background-tabs-on-select/issues/4#issuecomment-1865922537",
"url": "https://github.com/igorlogius/load-background-tabs-on-select/issues/4#issuecomment-1865922537",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by srjjgm** [comment]
Problem solved.
    I updated Tab Mix Plus to the newest test version made available by
    the author, and Load Background Tabs on Select worked normally.
    Thank you for your attention and I apologize for bothering you with
    a problem that was not yours.
    Thank you very much!
